DROP TABLE IF EXISTS `sys_template`;
CREATE TABLE `sys_template` (
  `uid` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `pid` int(10) unsigned NOT NULL DEFAULT 0,
  `tstamp` int(10) unsigned NOT NULL DEFAULT 0,
  `crdate` int(10) unsigned NOT NULL DEFAULT 0,
  `deleted` smallint(5) unsigned NOT NULL DEFAULT 0,
  `hidden` smallint(5) unsigned NOT NULL DEFAULT 0,
  `starttime` int(10) unsigned NOT NULL DEFAULT 0,
  `endtime` int(10) unsigned NOT NULL DEFAULT 0,
  `sorting` int(11) NOT NULL DEFAULT 0,
  `description` text DEFAULT NULL,
  `tx_impexp_origuid` int(11) NOT NULL DEFAULT 0,
  `title` varchar(255) NOT NULL DEFAULT '',
  `root` smallint(5) unsigned NOT NULL DEFAULT 0,
  `clear` smallint(5) unsigned NOT NULL DEFAULT 0,
  `constants` longtext DEFAULT NULL,
  `include_static_file` longtext DEFAULT NULL,
  `basedOn` longtext DEFAULT NULL,
  `includeStaticAfterBasedOn` smallint(5) unsigned NOT NULL DEFAULT 0,
  `config` longtext DEFAULT NULL,
  `static_file_mode` int(10) unsigned NOT NULL DEFAULT 0,
  PRIMARY KEY (`uid`),
  KEY `roottemplate` (`deleted`,`hidden`,`root`),
  KEY `parent` (`pid`,`deleted`,`hidden`)
);

CREATE TABLE `tt_content` (
  `tx_impexp_origuid` int(11) NOT NULL DEFAULT 0,
  `tx_mask_carousel_repeat` int(10) unsigned NOT NULL DEFAULT 0,
  `tx_mask_about_title` varchar(255) NOT NULL DEFAULT '',
  `tx_mask_about_desc` mediumtext DEFAULT NULL,
  `tx_mask_about_link` varchar(255) NOT NULL DEFAULT '',
  `tx_mask_about_link_label` varchar(255) NOT NULL DEFAULT '',
  `tx_mask_about_linkimage` int(10) unsigned NOT NULL DEFAULT 0,
  `tx_mask_about_image` int(10) unsigned NOT NULL DEFAULT 0,
  `tx_mask_chocolates_title` varchar(255) NOT NULL DEFAULT '',
  `tx_mask_chocolates_desc` mediumtext DEFAULT NULL,
  `tx_mask_chocolates_repeat` int(10) unsigned NOT NULL DEFAULT 0,
  `tx_mask_offer_title` varchar(255) NOT NULL DEFAULT '',
  `tx_mask_offer_subtitle` mediumtext DEFAULT NULL,
  `tx_mask_offer_link1` varchar(255) NOT NULL DEFAULT '',
  `tx_mask_offer_link1_label` varchar(255) NOT NULL DEFAULT '',
  `tx_mask_offer_img` int(10) unsigned NOT NULL DEFAULT 0,
  `tx_mask_offer_link2` varchar(255) NOT NULL DEFAULT '',
  `tx_mask_offer_link2_label` varchar(255) NOT NULL DEFAULT '',
  `tx_mask_offer_img2` int(10) unsigned NOT NULL DEFAULT 0,
  `tx_mask_testimonial_img` int(10) unsigned NOT NULL DEFAULT 0,
  `tx_mask_testimonial_title` varchar(255) NOT NULL DEFAULT '',
  `tx_mask_testimonial_repeat` int(10) unsigned NOT NULL DEFAULT 0,
  `tx_mask_contact_title` varchar(255) NOT NULL DEFAULT '',
  `tx_mask_contact_form` int(10) unsigned NOT NULL DEFAULT 0,
  `tx_mask_content_parent_uid` int(10) unsigned NOT NULL DEFAULT 0,
  `tx_mask_content_role` varchar(255) NOT NULL DEFAULT '',
  `tx_mask_content_tablenames` varchar(255) NOT NULL DEFAULT '',
  `tx_mask_footerpart3_title` varchar(255) NOT NULL DEFAULT '',
  `tx_mask_footerpart3_desc` mediumtext DEFAULT NULL,
  `tx_mask_footerpart4_title` varchar(255) NOT NULL DEFAULT '',
  `tx_mask_footerpart4_repeat` int(10) unsigned NOT NULL DEFAULT 0,
  `tx_mask_footerpart5_text` varchar(255) NOT NULL DEFAULT '',
  `tx_mask_footerpart5_link` varchar(255) NOT NULL DEFAULT '',
  `tx_mask_footerpart5_link_label` varchar(255) NOT NULL DEFAULT '',
  `tx_mask_google_map_link` mediumtext DEFAULT NULL,
  `tx_mask_background_choco` int(10) unsigned NOT NULL DEFAULT 0,
  `tx_mask_background_image` int(10) unsigned NOT NULL DEFAULT 0,
  `tx_mask_icon` int(10) unsigned NOT NULL DEFAULT 0,
  `tx_mask_social` int(10) unsigned NOT NULL DEFAULT 0,
  `tx_mask_background_img` int(10) unsigned NOT NULL DEFAULT 0,
  `tx_mask_button` varchar(255) NOT NULL DEFAULT '',
  `tx_mask_copyright` mediumtext DEFAULT NULL,
  `tx_mask_desc` mediumtext DEFAULT NULL,
  `tx_mask_link` varchar(255) NOT NULL DEFAULT '',
  KEY `tx_mask_content_parent_uid` (`tx_mask_content_parent_uid`)
);

DROP TABLE IF EXISTS `tx_mask_carousel_repeat`;
CREATE TABLE `tx_mask_carousel_repeat` (
  `uid` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `pid` int(10) unsigned NOT NULL DEFAULT 0,
  `tstamp` int(10) unsigned NOT NULL DEFAULT 0,
  `crdate` int(10) unsigned NOT NULL DEFAULT 0,
  `deleted` smallint(5) unsigned NOT NULL DEFAULT 0,
  `hidden` smallint(5) unsigned NOT NULL DEFAULT 0,
  `starttime` int(10) unsigned NOT NULL DEFAULT 0,
  `endtime` int(10) unsigned NOT NULL DEFAULT 0,
  `fe_group` varchar(255) NOT NULL DEFAULT '0',
  `sorting` int(11) NOT NULL DEFAULT 0,
  `editlock` smallint(5) unsigned NOT NULL DEFAULT 0,
  `sys_language_uid` int(11) NOT NULL DEFAULT 0,
  `l10n_parent` int(10) unsigned NOT NULL DEFAULT 0,
  `l10n_source` int(10) unsigned NOT NULL DEFAULT 0,
  `l10n_state` text DEFAULT NULL,
  `t3_origuid` int(10) unsigned NOT NULL DEFAULT 0,
  `l10n_diffsource` mediumblob DEFAULT NULL,
  `t3ver_oid` int(10) unsigned NOT NULL DEFAULT 0,
  `t3ver_wsid` int(10) unsigned NOT NULL DEFAULT 0,
  `t3ver_state` smallint(6) NOT NULL DEFAULT 0,
  `t3ver_stage` int(11) NOT NULL DEFAULT 0,
  `tx_mask_carousel_title` varchar(255) NOT NULL DEFAULT '',
  `tx_mask_carousel_subtitle` varchar(255) NOT NULL DEFAULT '',
  `tx_mask_carousel_link` varchar(255) NOT NULL DEFAULT '',
  `tx_mask_carousel_link_label` varchar(255) NOT NULL DEFAULT '',
  `parentid` int(11) NOT NULL DEFAULT 0,
  `parenttable` varchar(255) DEFAULT '',
  `tx_mask_link_image` int(10) unsigned NOT NULL DEFAULT 0,
  `tx_mask_carousel_image` int(10) unsigned NOT NULL DEFAULT 0,
  PRIMARY KEY (`uid`),
  KEY `parent` (`pid`,`deleted`,`hidden`),
  KEY `translation_source` (`l10n_source`),
  KEY `t3ver_oid` (`t3ver_oid`,`t3ver_wsid`)
);

DROP TABLE IF EXISTS `tx_mask_chocolates_repeat`;
CREATE TABLE `tx_mask_chocolates_repeat` (
  `uid` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `pid` int(10) unsigned NOT NULL DEFAULT 0,
  `tstamp` int(10) unsigned NOT NULL DEFAULT 0,
  `crdate` int(10) unsigned NOT NULL DEFAULT 0,
  `deleted` smallint(5) unsigned NOT NULL DEFAULT 0,
  `hidden` smallint(5) unsigned NOT NULL DEFAULT 0,
  `starttime` int(10) unsigned NOT NULL DEFAULT 0,
  `endtime` int(10) unsigned NOT NULL DEFAULT 0,
  `fe_group` varchar(255) NOT NULL DEFAULT '0',
  `sorting` int(11) NOT NULL DEFAULT 0,
  `editlock` smallint(5) unsigned NOT NULL DEFAULT 0,
  `sys_language_uid` int(11) NOT NULL DEFAULT 0,
  `l10n_parent` int(10) unsigned NOT NULL DEFAULT 0,
  `l10n_source` int(10) unsigned NOT NULL DEFAULT 0,
  `l10n_state` text DEFAULT NULL,
  `t3_origuid` int(10) unsigned NOT NULL DEFAULT 0,
  `l10n_diffsource` mediumblob DEFAULT NULL,
  `t3ver_oid` int(10) unsigned NOT NULL DEFAULT 0,
  `t3ver_wsid` int(10) unsigned NOT NULL DEFAULT 0,
  `t3ver_state` smallint(6) NOT NULL DEFAULT 0,
  `t3ver_stage` int(11) NOT NULL DEFAULT 0,
  `tx_mask_chocolates_images` int(10) unsigned NOT NULL DEFAULT 0,
  `tx_mask_chocolates_title2` varchar(255) NOT NULL DEFAULT '',
  `tx_mask_chocolates_subtitle` varchar(255) NOT NULL DEFAULT '',
  `tx_mask_chocolates_price` varchar(255) NOT NULL DEFAULT '',
  `tx_mask_chocolates_link` varchar(255) NOT NULL DEFAULT '',
  `tx_mask_chocolateslink_label` varchar(255) NOT NULL DEFAULT '',
  `parentid` int(11) NOT NULL DEFAULT 0,
  `parenttable` varchar(255) DEFAULT '',
  PRIMARY KEY (`uid`),
  KEY `parent` (`pid`,`deleted`,`hidden`),
  KEY `translation_source` (`l10n_source`),
  KEY `t3ver_oid` (`t3ver_oid`,`t3ver_wsid`)
);

DROP TABLE IF EXISTS `tx_mask_footerpart4_repeat`;
CREATE TABLE `tx_mask_footerpart4_repeat` (
  `uid` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `pid` int(10) unsigned NOT NULL DEFAULT 0,
  `tstamp` int(10) unsigned NOT NULL DEFAULT 0,
  `crdate` int(10) unsigned NOT NULL DEFAULT 0,
  `deleted` smallint(5) unsigned NOT NULL DEFAULT 0,
  `hidden` smallint(5) unsigned NOT NULL DEFAULT 0,
  `starttime` int(10) unsigned NOT NULL DEFAULT 0,
  `endtime` int(10) unsigned NOT NULL DEFAULT 0,
  `fe_group` varchar(255) NOT NULL DEFAULT '0',
  `sorting` int(11) NOT NULL DEFAULT 0,
  `editlock` smallint(5) unsigned NOT NULL DEFAULT 0,
  `sys_language_uid` int(11) NOT NULL DEFAULT 0,
  `l10n_parent` int(10) unsigned NOT NULL DEFAULT 0,
  `l10n_source` int(10) unsigned NOT NULL DEFAULT 0,
  `l10n_state` text DEFAULT NULL,
  `t3_origuid` int(10) unsigned NOT NULL DEFAULT 0,
  `l10n_diffsource` mediumblob DEFAULT NULL,
  `t3ver_oid` int(10) unsigned NOT NULL DEFAULT 0,
  `t3ver_wsid` int(10) unsigned NOT NULL DEFAULT 0,
  `t3ver_state` smallint(6) NOT NULL DEFAULT 0,
  `t3ver_stage` int(11) NOT NULL DEFAULT 0,
  `tx_mask_footerpart4_links` varchar(255) NOT NULL DEFAULT '',
  `tx_mask_footerpart4_link_label` varchar(255) NOT NULL DEFAULT '',
  `tx_mask_footerpart4_icons` varchar(255) NOT NULL DEFAULT '',
  `parentid` int(11) NOT NULL DEFAULT 0,
  `parenttable` varchar(255) DEFAULT '',
  `tx_mask_icons` int(10) unsigned NOT NULL DEFAULT 0,
  PRIMARY KEY (`uid`),
  KEY `parent` (`pid`,`deleted`,`hidden`),
  KEY `translation_source` (`l10n_source`),
  KEY `t3ver_oid` (`t3ver_oid`,`t3ver_wsid`)
);

DROP TABLE IF EXISTS `tx_mask_testimonial_repeat`;
CREATE TABLE `tx_mask_testimonial_repeat` (
  `uid` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `pid` int(10) unsigned NOT NULL DEFAULT 0,
  `tstamp` int(10) unsigned NOT NULL DEFAULT 0,
  `crdate` int(10) unsigned NOT NULL DEFAULT 0,
  `deleted` smallint(5) unsigned NOT NULL DEFAULT 0,
  `hidden` smallint(5) unsigned NOT NULL DEFAULT 0,
  `starttime` int(10) unsigned NOT NULL DEFAULT 0,
  `endtime` int(10) unsigned NOT NULL DEFAULT 0,
  `fe_group` varchar(255) NOT NULL DEFAULT '0',
  `sorting` int(11) NOT NULL DEFAULT 0,
  `editlock` smallint(5) unsigned NOT NULL DEFAULT 0,
  `sys_language_uid` int(11) NOT NULL DEFAULT 0,
  `l10n_parent` int(10) unsigned NOT NULL DEFAULT 0,
  `l10n_source` int(10) unsigned NOT NULL DEFAULT 0,
  `l10n_state` text DEFAULT NULL,
  `t3_origuid` int(10) unsigned NOT NULL DEFAULT 0,
  `l10n_diffsource` mediumblob DEFAULT NULL,
  `t3ver_oid` int(10) unsigned NOT NULL DEFAULT 0,
  `t3ver_wsid` int(10) unsigned NOT NULL DEFAULT 0,
  `t3ver_state` smallint(6) NOT NULL DEFAULT 0,
  `t3ver_stage` int(11) NOT NULL DEFAULT 0,
  `tx_mask_testimonial_img2` int(10) unsigned NOT NULL DEFAULT 0,
  `tx_mask_testimonial_title2` varchar(255) NOT NULL DEFAULT '',
  `tx_mask_testimonial_desc` mediumtext DEFAULT NULL,
  `parentid` int(11) NOT NULL DEFAULT 0,
  `parenttable` varchar(255) DEFAULT '',
  `tx_mask_desc` mediumtext DEFAULT NULL,
  PRIMARY KEY (`uid`),
  KEY `parent` (`pid`,`deleted`,`hidden`),
  KEY `translation_source` (`l10n_source`),
  KEY `t3ver_oid` (`t3ver_oid`,`t3ver_wsid`)
);